// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Company struct {
	ID       string  `json:"id"`
	Name     string  `json:"name"`
	PhotoURL *string `json:"photoUrl,omitempty"`
}

type Group struct {
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
	PhotoURL    *string `json:"photoUrl,omitempty"`
}

type Message struct {
	ID         string  `json:"id"`
	SenderID   string  `json:"senderId"`
	ReceiverID string  `json:"receiverId"`
	GroupID    string  `json:"groupId"`
	Content    *string `json:"content,omitempty"`
	MediaURL   *string `json:"mediaUrl,omitempty"`
	Timestamp  string  `json:"timestamp"`
}

type Mutation struct {
}

type Query struct {
}

type Subscription struct {
}

type User struct {
	ID          string   `json:"id"`
	Username    string   `json:"username"`
	DisplayName *string  `json:"displayName,omitempty"`
	PhotoURL    *string  `json:"photoUrl,omitempty"`
	Company     *Company `json:"company,omitempty"`
}
